# Generated by Django 6.0 on 2025-12-09 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('s3_bucket', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('lambda_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_metadata',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['s3_key'], name='file_metada_s3_key_cdda3d_idx'), models.Index(fields=['created_at'], name='file_metada_created_380454_idx')],
            },
        ),
    ]
